// <auto-generated />
namespace IOT.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IOTDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IOTDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201709201656245_IOTDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
